server:
  port: 8441

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminication?createDatabaseIfNotExist=true
    username: root
    password: "#include<winuser.h>"

security:
  jwt:
    uri: /authenticationService/**
    header: Authorization
    prefix: Bearer
    expiration: 24*60*60
    secret: f54148
